### ISSUE TITLE
Are float32 files converted to Values [2]int and back to float64?

### ISSUE THREAD

**Issue by charneykaye** [youpy/go-wav#1]
This is a deal-breaker here for me, in reader.go:

    func (r *Reader) FloatValue(sample Sample, channel uint) float64 {
        // XXX
        return float64(r.IntValue(sample, channel)) / math.Pow(2, float64(r.format.BitsPerSample))
    }

As is, this drastically distorts the levels of the source audio. What I need are the unmodified original float32 values converted to float64!

**Comment by youpy** [comment]
Thanks.

I just [added](https://github.com/youpy/go-wav/commit/93664fc437046a39a1fc88deb3f78c7010b0bfc2
) quick-fix for 32-bit float WAV.

**Comment by charneykaye** [comment]
Nice! Thanks
