### ISSUE TITLE
Audio duration

### ISSUE THREAD

**Issue by pablodz** [youpy/go-wav#6]
Hello there,

is possible to know the duration of the wave file in milliseconds?

**Comment by youpy** [comment]
You can get the duration of the file from version v0.3.0.

```go
reader := NewReader("a.wav")
duration, err := reader.Duration()
if err != nil {
  panic(err)
}

fmt.Println(duration.Milliseconds())
```

**Comment by pablodz** [comment]
> You can get the duration of the file from version v0.3.0.
> 
> ```go
> reader := NewReader("a.wav")
> duration, err := reader.Duration()
> if err != nil {
>   panic(err)
> }
> 
> fmt.Println(duration.Milliseconds())
> ```

Thanks a lot! @youpy
